# Generated by Django 5.0.1 on 2024-05-01 15:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the student's name", max_length=100)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('roll_number', models.CharField(help_text="Enter the student's roll number", max_length=20, unique=True)),
                ('email', models.EmailField(help_text="Enter the student's email address", max_length=254, unique=True)),
                ('date_of_birth', models.DateField(help_text="Enter the student's date of birth")),
                ('address', models.TextField(blank=True, help_text="Enter the student's address", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Enter the date of the presence record')),
                ('present', models.BooleanField(default=False, help_text='Whether the student was present or not')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.student')),
            ],
        ),
    ]
