# Generated by Django 5.0.6 on 2024-06-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='presencerecord',
            table='dashboard_presencerecord',
        ),
    ]
