# Generated by Django 5.0.6 on 2024-06-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent_today',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='present_today',
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
