# Generated by Django 5.0.6 on 2024-06-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_presencerecord_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PresenceRecord',
            new_name='PresenceRecords',
        ),
    ]
