# Generated by Django 5.0.6 on 2024-06-21 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_attendance_absent_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_absent',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_present',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_students',
            field=models.IntegerField(),
        ),
    ]
