# Generated by Django 5.0.4 on 2024-05-01 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
