# Generated by Django 5.0.4 on 2024-05-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactformsubmission_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsubmission',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
