# Generated by Django 5.0.4 on 2024-06-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contactformsubmission_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='message',
            field=models.TextField(),
        ),
    ]
